CREATE TABLE orders(
  id INT (11) NOT NULL AUTO_INCREMENT,
  name VARCHAR (100) NOT NULL,
  address VARCHAR (300) NOT NULL,
  city VARCHAR (100) NOT NULL,
  giftWrap TINYINT (1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;
